Test if install folder already exists

diff --git a/bin/ssl-certs b/bin/ssl-certs
--- a/bin/ssl-certs
+++ b/bin/ssl-certs
@@ -139,6 +139,11 @@ __ssl-certs_certbot_install()
         exit $EXIT_CODE_OK
     fi
 
+    if [ -d "$CERTBOT_PATH" ]; then
+        echo "[ERROR] The folder \"$CERTBOT_PATH\" already exists. Please remove it and try again."
+        exit $EXIT_CODE_ERROR
+    fi
+
     echo "[INFO] Certbot will be installed in $CERTBOT_PATH and a symlink will be created in \"/usr/bin\" folder..."
     git=$(which git)
     if [ -z "$git" ]; then
