Optimize certbot commands

diff --git a/bin/ssl-certs b/bin/ssl-certs
--- a/bin/ssl-certs
+++ b/bin/ssl-certs
@@ -113,32 +113,37 @@ __ssl-certs_certbot_install()
 {
     __certbot_exists
     if [ $? -eq $TRUE ]; then
-        if [ ! -L "/usr/bin/certbot-auto" ]; then
-            ln -s "$CERTBOT_DEFAULT_PATH/certbot-auto" "/usr/bin/certbot-auto"
+        if [ ! -L "$CERTBOT_SYMLINK" ]; then
+            ln -s "$CERTBOT_PATH/certbot-auto" "$CERTBOT_SYMLINK" &>/dev/null
         fi
         __certbot_exists
         echo "[INFO] Certbot is already installed and can be execute using \"$certbot\" command."
         exit $EXIT_CODE_OK
     fi
 
-    echo "[INFO] Certbot will be installed in $CERTBOT_DEFAULT_PATH and a symlink will be created in \"/usr/bin\" folder..."
+    echo "[INFO] Certbot will be installed in $CERTBOT_PATH and a symlink will be created in \"/usr/bin\" folder..."
     git=$(which git)
     if [ -z "$git" ]; then
         "[ERROR] Git is not installed. Please install it before running this command again."
         exit $EXIT_CODE_ERROR
     fi
 
-    git clone "$CERTBOT_REPO" "$CERTBOT_DEFAULT_PATH"
-    if [ ! -f "$CERTBOT_DEFAULT_PATH/certbot-auto" ]; then
+    git clone "$CERTBOT_REPO" "$CERTBOT_PATH"
+    if [ ! -f "$CERTBOT_PATH/certbot-auto" ]; then
         echo "[ERROR] Could not install certbot. Please try again."
         exit $EXIT_CODE_ERROR
     fi
 
-    ln -s "$CERTBOT_DEFAULT_PATH/certbot-auto" "/usr/bin/certbot-auto"
-    if [ ! -L "/usr/bin/certbot-auto" ]; then
-        "[ERROR] Could not symlink certbot-auto but it was correctly installed in \"$CERTBOT_DEFAULT_PATH\" folder."
+    ln -s "$CERTBOT_PATH/certbot-auto" "$CERTBOT_SYMLINK" &>/dev/null
+    if [ ! -L "$CERTBOT_SYMLINK" ]; then
+        "[ERROR] Could not symlink certbot-auto but it was correctly installed in \"$CERTBOT_PATH\" folder."
         exit $EXIT_CODE_ERROR
     fi
+
+    __certbot_exists
+    echo "Installing certbot dependencies..."
+    $certbot --os-packages-only
+    echo "Certbot dependencies installed."
 
     echo "[INFO] Certbot was correctly installed. You can use it with \"certbot-auto\" command."
 }
@@ -153,19 +158,24 @@ __ssl-certs_certbot_remove()
         exit $EXIT_CODE_OK
     fi
 
-    echo "[INFO] Certbot will be remove from \"$CERTBOT_DEFAULT_PATH\" and the symlink will be deleted..."
-    rm -rf "$CERTBOT_DEFAULT_PATH"
-    if [ -d "$CERTBOT_DEFAULT_PATH" ]; then
-        echo "[ERROR] Could not remove certbot folder. Please try again."
-        exit $EXIT_CODE_ERROR
+    if [ -L "$CERTBOT_SYMLINK" ]; then
+        echo "[INFO] Removing certbot symlink..."
+        rm "$CERTBOT_SYMLINK" &>/dev/null
+        if [ ! $? -eq $EXIT_CODE_OK ]; then
+            echo "[ERROR] Could not remove certbot-auto symlink."
+            exit $EXIT_CODE_ERROR
+        else
+            echo "[INFO] Certbot symlink removed."
+        fi
     fi
 
-    if [ -f "/usr/bin/certbot-auto" ]; then
-        rm "/usr/bin/certbot-auto"
-        if [ -L "/usr/bin/certbot-auto" ]; then
-            "[ERROR] Could not remove certbot-auto symlink but it was correctly removed from \"$CERTBOT_DEFAULT_PATH\" folder."
-            exit $EXIT_CODE_ERROR
-        fi
+    echo "[INFO] Certbot will be remove from \"$CERTBOT_PATH\"..."
+    rm -rf "$CERTBOT_PATH" &>/dev/null
+    if [ -d "$CERTBOT_PATH" ]; then
+        echo "[ERROR] Could not remove certbot folder. Please try again."
+        exit $EXIT_CODE_ERROR
+    else
+        echo "[INFO] Certbot application removed."
     fi
 
     echo "[INFO] Certbot was correctly removed."
@@ -181,7 +191,11 @@ __ssl-certs_certbot_update()
         exit $EXIT_CODE_ERROR
     fi
 
-    (cd "$CERTBOT_DEFAULT_PATH" && git pull)
+    (cd "$CERTBOT_PATH" && git pull)
+
+    echo "Updating certbot dependencies..."
+    $certbot --os-packages-only
+    echo "Certbot dependencies updated."
 }
 # ---------- end: certbot update ----------
 
