Get cert-name from configuration to look for issued certificate

diff --git a/bin/ssl-certs b/bin/ssl-certs
--- a/bin/ssl-certs
+++ b/bin/ssl-certs
@@ -331,12 +331,14 @@ __ssl-certs_get()
             exit $EXIT_CODE_ERROR
         fi
         echo -e "$concat_config" > "$tmp_config"
+        cert_name=$(echo "$concat_config" | grep "cert-name" | sed -E 's/cert-name( +)?=( +)?//')
 
         $certbot certonly --config "$tmp_config" $extra_options
         rm "$tmp_config" 2>/dev/null
         echo "[INFO] Finished executing certbot for config file \"$f\" with certificate name \"$cert_name\""
         echo
 
+        # TODO: Verify if certificates where registered (check return value $? for this and existance in default certificate folder etc/letsencrypt/live/$cert_names)
     done
 }
 
