Code the get command

diff --git a/bin/ssl-certs b/bin/ssl-certs
--- a/bin/ssl-certs
+++ b/bin/ssl-certs
@@ -283,7 +283,38 @@ __ssl-certs_help_commands()
 
 __ssl-certs_get()
 {
-    echo "ssl-certs get"
+    config_files=$(find "$CONFIG_DOMAINS_PATH" -maxdepth 1 -type f -iname '*.ini' ! -iname '.*' | sort)
+    OIFS="$IFS"; IFS=$'\n'; configs=($config_files); IFS="$OIFS"; configc=${#configs[@]}
+
+    if [ $configc -eq 0 ]; then
+        echo "[INFO] No domain configuration files found."
+        exit $EXIT_CODE_OK
+    fi
+
+    for f in "${configs[@]}"
+    do
+        __concat_config_files "$CONFIG_FILE" "$f"
+        if [ $? -eq $FALSE ]; then
+            echo "[ERROR] There seems to be an error with your configuration. Fix the problems and try again."
+            exit $EXIT_CODE_ERROR
+        fi
+        
+        if [ $? -eq $FALSE ]; then
+            echo "[ERROR] An error occurred while concatenating config files."
+            exit $EXIT_CODE_ERROR
+        fi
+
+        tmp_config=$(mktemp "/tmp/ssl-certs-config-XXXXXXXX.tmp")
+        if [ $? -eq $FALSE ]; then
+            echo "[ERROR] An error occurred while saving the temp config file."
+            exit $EXIT_CODE_ERROR
+        fi
+        echo -e "$concat_config" > "$tmp_config"
+        
+        # TODO: execute certbot with the options and the temp config file
+        
+        rm "$tmp_config" 2>/dev/null
+    done
 }
 
 # ========== end: get ==========
