Encapsulated certbot_or_fail functionality

diff --git a/lib/ssl-certs-utils b/lib/ssl-certs-utils
--- a/lib/ssl-certs-utils
+++ b/lib/ssl-certs-utils
@@ -36,6 +36,25 @@ __certbot_exists()
     return $TRUE
 }
 
+# __certbot_or_fail(int exit code, string message)
+# Verifies if certbot exists or script execution will fail.
+# Sets the variable $certbot to the path of the executable.
+__certbot_or_fail()
+{
+    exit_code=$1
+    message=$2
+
+    if [ -z "$exit_code" ]; then
+        exit_code=$EXIT_CODE_ERROR
+    fi
+
+    __certbot_exists
+    if [ $? -eq $FALSE ]; then
+        echo "$message"
+        exit $exit_code
+    fi
+}
+
 # __concat_config_files($dest, $config1, $config2, ...)
 # Concatenates the given config files into a destination file.
 # Returns true 
